// import config from '../../config';
import Config from 'react-native-config';
const getURLs = action => {
  const baseURL = Config.API_ENDPOINT;
  switch (action) {
    case 'login':
      return `${baseURL}/user/auth/login`;
    case 'register':
      return `${baseURL}/user/auth/register/mobile`;
    case 'forgot':
      return `${baseURL}/user/auth/forgot/password`;
    case 'resend-otp':
      return `${baseURL}/user/auth/resend/otp`;
    case 'verify-mobile-otp':
      return `${baseURL}/user/auth/verify-otp`;
    case 'update-password':
      return `${baseURL}/user/auth/update/password`;
    case 'file-upload':
      return `${baseURL}/user/profile/file/upload`;
    case 'profile-update':
      return `${baseURL}/user/profile/info/update`;
    case 'prfoessional-update':
      return `${baseURL}/user/professional/info/update`;
    case 'add-clinic':
      return `${baseURL}/profile/add/clinic`;
    case 'get-clinics':
      return `${baseURL}/user/get/clinics`;
    case 'get-clinics-bynumber':
      return `${baseURL}/user/get/clinic/by/number`;
    case 'clinic-otp-number':
      return `${baseURL}/user/otp/doctor/bynumber`;
    case 'add-role':
      return `${baseURL}/user/add/role`;
    case 'add-cons-partner':
      return `${baseURL}/user/add/role/cons-partner`;
    case 'reg-complete':
      return `${baseURL}/user/complete/registration`;
    case 'get-forum':
      return `${baseURL}/forum/get/list`;
    case 'create-forum':
      return `${baseURL}/forum/create`;
    case 'forum-likelist':
      return `${baseURL}/forum/like/list`;
    case 'like-forum':
      return `${baseURL}/forum/like/post`;
    case 'bookmark-forum':
      return `${baseURL}/forum/bookmark/update`;
    case 'get-all-bookmarked':
      return `${baseURL}/forum/get/bookmarked`;
    case 'get-forum-detial':
      return `${baseURL}/forum/detail`;
    case 'get-forum-comments':
      return `${baseURL}/forum/comment/list`;
    case 'comment-forum':
      return `${baseURL}/forum/comment/post`;
    case 'forum-with-image':
      return `${baseURL}/forum/create/by/formdata`;
    case 'email-otp':
      return `${baseURL}/user/email/generate/otp`;
    case 'verify-email-otp':
      return `${baseURL}/user/email/verify/otp`;
    case 'get-associates':
      return `${baseURL}/profile/get/associates`;
    case 'pending-request':
      return `${baseURL}/profile/pending/request`;
    case 'approve-request':
      return `${baseURL}/profile/pending/request/approve`;
    case 'cancel-request':
      return `${baseURL}/profile/pending/request/cancel`;
    case 'create-support':
      return `${baseURL}/profile/create/ticket`;
    case 'event-list':
      return `${baseURL}/event/get/list`;
    case 'event-detail':
      return `${baseURL}/event/get/detail`;
    case 'get-residents':
      return `${baseURL}/profile/get/resident`;
    case 'book-event':
      return `${baseURL}/event/book`;
    case 'get-event-attendees':
      return `${baseURL}/event/get/attendees`;
    case 'get-booked-my-evnets':
      return `${baseURL}/event/my/events`;
    case 'cancel-event-booking':
      return `${baseURL}/event/cancel/booking`;
    case 'get-appoinments':
      return `${baseURL}/patient/appoinments`;
    case 'create-patient':
      return `${baseURL}/patient/create`;
    case 'create-treatment':
      return `${baseURL}/patient/create/treatment`;
    case 'create-record':
      return `${baseURL}/patient/create/record`;
    case 'all-patient':
      return `${baseURL}/patient/all`;
    case 'patient-detail':
      return `${baseURL}/patient/detail`;
    case 'get-treatments':
      return `${baseURL}/patient/treatments`;
    case 'get-records':
      return `${baseURL}/patient/records`;
    case 'add-images-record':
      return `${baseURL}/patient/add/image/record`;
    case 'update-record':
      return `${baseURL}/patient/record`;
    case 'filter-patient':
      return `${baseURL}/patient/filter`;
    case 'filter-event':
      return `${baseURL}/event/filter`;
    default:
      return baseURL;
  }
};

export default getURLs;
